version: '3'
services:
  elasticsearch:
    build: ./docker/elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./docker/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./docker/elasticsearch/config/synonyms.txt:/usr/share/elasticsearch/config/synonyms.txt
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms1g -Xmx1g
#  elasticsearch-head:
#    image: mobz/elasticsearch-head:5
#    ports:
#      - "9100:9100"
#  redis:
#    image: redis:3.2.4
#    command: redis-server --appendonly yes --requirepass password
#    ports:
#      - "6379:6379"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    ports:
      - 5601:5601